- name: deploy code image
  docker_container:
    name: flaskcicd 
    image: "cicd-flask:{{ lookup('env','imagetag') | default('latest', true) }}"
    state: started 
    recreate: yes
    restart_policy: always
    published_ports:
      - 80:80
  become: yes
