- name: deploy code image
  docker_container:
    name: flaskcicd 
    image: cicd-flask 
    state: started 
    recreate: yes
    restart_policy: always
    published_ports:
      - 80:80
  become: yes
